# Generated by Django 4.2.28 on 2026-02-10 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. PL, LL, BL1', max_length=10, unique=True)),
                ('country', models.CharField(max_length=60)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('api_id', models.IntegerField(blank=True, help_text='External API league ID', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Display order – lower = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leagues',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=30)),
                ('code', models.CharField(blank=True, default='', max_length=5)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=60)),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='core.league')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.league')),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-start_date'],
                'unique_together': {('league', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('match_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('timed', 'Timed'), ('in_play', 'In Play'), ('paused', 'Paused'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='scheduled', max_length=15)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_half_score', models.IntegerField(blank=True, null=True)),
                ('away_half_score', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True after kickoff – no more prediction changes')),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.season')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['match_date'],
                'indexes': [models.Index(fields=['status', 'match_date'], name='matches_status_23ee60_idx'), models.Index(fields=['league', 'match_date'], name='matches_league__96de5f_idx')],
            },
        ),
    ]
