# Generated by Django 4.2.28 on 2026-02-22 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def seed_epl_priority(apps, schema_editor):
    """Give Premier League 50 % of the subscription daily quota by default."""
    League = apps.get_model("core", "League")
    LeagueAccessRule = apps.get_model("core", "LeagueAccessRule")

    # Premier League is typically stored with code 'PL' (football-data.org) or 'EPL'
    epl = League.objects.filter(code__in=["PL", "EPL"]).first()
    if epl:
        LeagueAccessRule.objects.update_or_create(
            league=epl,
            defaults={"subscription_share_pct": 50.0},
        )


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_share_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage (0–100) of the subscriber's daily prediction limit to allocate to this league. 0 = equal share with other zero-pct leagues. Example: set Premier League to 50 → EPL gets half the daily quota.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rule",
                        to="core.league",
                    ),
                ),
            ],
            options={
                "db_table": "league_access_rules",
                "ordering": ["-subscription_share_pct", "league__priority"],
            },
        ),
        migrations.RunPython(seed_epl_priority, reverse_code=reverse_seed),
    ]
