# Generated by Django 4.2.28 on 2026-02-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_league_access_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="is_seasonal",
            field=models.BooleanField(
                default=False,
                help_text="True for competitions that only occur during certain months (e.g. Champions League)",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="league_type",
            field=models.CharField(
                choices=[
                    ("domestic", "Domestic League"),
                    ("continental", "Continental Competition"),
                    ("international", "International Competition"),
                ],
                default="domestic",
                help_text="Category of competition",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season_months",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON list of month numbers (1-12) when this league is active. Empty = year-round. E.g. [9,10,11,12,1,2,3,4,5,6] for Champions League.",
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="code",
            field=models.CharField(
                help_text="Short code, e.g. PL, LL, BL1, UCL",
                max_length=10,
                unique=True,
            ),
        ),
    ]
