# Generated by Django 4.2.28 on 2026-02-28 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_europa_conference_leagues"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Alternative team name from an external source",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which source uses this name (e.g. 'predictz', 'forebet', 'espn')",
                        max_length=80,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "team aliases",
                "db_table": "team_aliases",
                "ordering": ["alias"],
            },
        ),
    ]
