# Generated by Django 4.2.28 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchannel',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('whatsapp', 'WhatsApp Pay')], max_length=20),
        ),
    ]
