# Generated by Django 4.2.28 on 2026-02-10 12:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('east_africa', 'East Africa'), ('west_africa', 'West Africa'), ('europe', 'Europe'), ('americas', 'Americas'), ('asia', 'Asia'), ('global', 'Global / Other')], default='global', max_length=20)),
                ('country_code', models.CharField(blank=True, default='', max_length=3)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=5)),
                ('detected_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_cached_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('signup_bonus_granted', models.BooleanField(default=False)),
                ('signup_bonus_credits', models.IntegerField(default=3)),
                ('anonymous_views_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='LoginBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('signup', 'Signup Bonus'), ('referral', 'Referral Bonus'), ('promo', 'Promotional Bonus')], max_length=20)),
                ('credits_granted', models.IntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_bonuses',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('credits_used', models.IntegerField(default=1)),
                ('is_free', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction_usage',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='prediction__user_id_92065d_idx')],
            },
        ),
    ]
