# Generated by Django 4.2.28 on 2026-02-10 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('region', models.CharField(default='global', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('single_prediction_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('new_subscribers', models.IntegerField(default=0)),
                ('churned_subscribers', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('most_profitable_tier', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'revenue_snapshots',
                'ordering': ['-date'],
                'unique_together': {('date', 'region')},
            },
        ),
        migrations.CreateModel(
            name='PredictionStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_predictions', models.IntegerField(default=0)),
                ('predictions_consumed', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('most_predicted_outcome', models.CharField(blank=True, default='', max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_stats', to='core.league')),
            ],
            options={
                'db_table': 'prediction_stats',
                'ordering': ['-date'],
                'unique_together': {('league', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AccuracyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('incorrect_predictions', models.IntegerField(default=0)),
                ('pending_predictions', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('home_win_accuracy', models.FloatField(default=0.0)),
                ('draw_accuracy', models.FloatField(default=0.0)),
                ('away_win_accuracy', models.FloatField(default=0.0)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, help_text='Null = overall (all leagues)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='core.league')),
            ],
            options={
                'db_table': 'accuracy_records',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period', 'period_start'], name='accuracy_re_period_639488_idx'), models.Index(fields=['league', 'period'], name='accuracy_re_league__3a2639_idx')],
            },
        ),
    ]
